---
name: Default

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container: lesovsky/pgcenter-testing:0.0.6

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prepare test environment
        run: prepare-test-environment.sh
      - name: Run lint
        run: make lint
      - name: Run test
        run: make test
      - name: Build
        run: make build
      - name: Install
        run: make install
      - name: Run E2E tests
        run: ./testing/e2e.sh
